### ISSUE TITLE
Migration error after install

### ISSUE THREAD

**Issue by tehfink** [marksweb/djangocms-ads#20]
After installing with pip on django-cms==3.11.1, Django==3.2.18, & python==3.8.10, and running:
`python manage.py migrate`

This error:
```
…
django.db.migrations.exceptions.NodeNotFoundError: Migration djangocms_ads.0001_initial dependencies reference nonexistent parent node ('cms', '0034_remove_pagecontent_placeholders')
```

was resolved by deleting the migrations in the migration folder: 
`virtualenv/lib/python3.8/site-packages/djangocms_ads/migrations`
and running again:
`python manage.py makemigrations && python manage.py migrate`

**Comment by marksweb** [comment]
@tehfink thanks for flagging. Looks like I generated the migration while using this with django-cms 4 which is why you're seeing that with v3.
